<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Shopgate\WebCheckout\ViewModel\JavaScriptConfiguration $jsConfig
 * @var \Shopgate\WebCheckout\ViewModel\CustomerData $customer
 */
$jsConfig = $block->getData('jsConfig');
$customer = $block->getData('customer');
$jsConfig->addProperties(['token' => $customer->getAuthToken()]);
?>
<script type='text/x-magento-init'>
    {
        "*": {
            "Shopgate_WebCheckout/js/init": <?= $jsConfig->toJson() ?>,
            "Shopgate_WebCheckout/js/spinner": {
              "icon": "<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>"
            }
    }
}
</script>
