<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<script>
    require([
        'jquery',
        'loader',
    ], function ($) {
        $('body').append($('<div id="loader"/>'));

        const $loader = $('#loader').loader({
            icon: "<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>"
        });

        $loader.loader('show');
    });
</script>
