<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Shopgate\WebCheckout\ViewModel\JavaScriptConfiguration $jsConfig
 * @var \Shopgate\WebCheckout\ViewModel\CustomerData $customer
 */
$jsConfig = $block->getData('jsConfig');
$customer = $block->getData('customer');
$jsConfig->addProperty('token', $customer->getAuthToken());
?>
<script type='text/x-magento-init'>
    {
        "*": {
            "Shopgate_WebCheckout/js/init": <?= $jsConfig->toJson() ?>
    }
}
</script>
<script>
    require([
        'jquery',
        'loader',
    ], function ($) {
        $('body').append($('<div id="loader"/>'));

        const $loader = $('#loader').loader({
            icon: "<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>"
        });

        $loader.loader('show');
    });
</script>
